######################################################################
# Automatically generated by qmake (2.01a) mer. oct. 21 09:55:29 2009
######################################################################

TEMPLATE = lib
CONFIG += plugin
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

DESTDIR = ../

# Input
HEADERS += widgetexec.h
SOURCES += widgetexec.cpp
