# #####################################################################
# Automatically generated by qmake (2.01a) mer. oct. 21 09:55:29 2009
# #####################################################################
TEMPLATE = lib
CONFIG += plugin
CONFIG += release
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
DESTDIR = ../

# Input
HEADERS += widgetexec.h \
    widgetexecerrorstab.h \
    widgetexectab.h
SOURCES += widgetexec.cpp \
    widgetexecerrorstab.cpp \
    widgetexectab.cpp
