# #####################################################################
# Automatically generated by qmake (2.01a) mer. sept. 30 09:26:40 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    window.cpp \
    apropos.cpp \
    princwidget.cpp
HEADERS += window.h \
    apropos.h \
    princwidget.h
