# #####################################################################
# Automatically generated by qmake (2.01a) mer. oct. 21 09:55:29 2009
# #####################################################################
TEMPLATE = lib
CONFIG += plugin
CONFIG += release
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
DESTDIR = ../

# Input
HEADERS += widgetglossaire.h \
    editionvariable.h
SOURCES += widgetglossaire.cpp \
    editionvariable.cpp
RESOURCES += icons.qrc
FORMS += 
