#ifndef ANALYSE_GLOBAL_H
#define ANALYSE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ANALYSESEMANTIQUE_LIBRARY)
#  define ANALYSESEMANTIQUESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ANALYSESEMANTIQUESHARED_EXPORT Q_DECL_IMPORT
#endif

#if defined(ANALYSESYNTAXIQUE_LIBRARY)
#  define ANALYSESYNTAXIQUESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ANALYSESYNTAXIQUESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ANALYSE_GLOBAL_H
